// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaskFlow.Api.Data;

#nullable disable

namespace TaskFlow.Api.Migrations
{
    [DbContext(typeof(TaskFlowContext))]
    [Migration("20260917132952_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("TaskFlow.Api.Models.TaskItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Priority")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Planning",
                            CreatedAt = new DateTime(2026, 9, 1, 9, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Define entities, relationships and constraints for TaskFlow.",
                            IsCompleted = true,
                            Priority = 2,
                            Title = "Design the database schema"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Backend",
                            CreatedAt = new DateTime(2026, 9, 3, 9, 0, 0, 0, DateTimeKind.Utc),
                            Description = "CRUD endpoints with ASP.NET Core and EF Core.",
                            IsCompleted = true,
                            Priority = 2,
                            Title = "Build the Tasks REST API"
                        },
                        new
                        {
                            Id = 3,
                            Category = "Frontend",
                            CreatedAt = new DateTime(2026, 9, 5, 9, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Fetch tasks from the API and render the board.",
                            DueDate = new DateTime(2026, 9, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsCompleted = false,
                            Priority = 1,
                            Title = "Connect the React frontend"
                        },
                        new
                        {
                            Id = 4,
                            Category = "Docs",
                            CreatedAt = new DateTime(2026, 9, 6, 9, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Document setup steps and add screenshots.",
                            IsCompleted = false,
                            Priority = 0,
                            Title = "Write the README"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
